In [2]:
import pandas as pd
import io
import numpy as np

In [3]:
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]

In [4]:
pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))

MultiIndex(levels=[[1, 2], ['blue', 'red']],
           codes=[[0, 0, 1, 1], [1, 0, 1, 0]],
           names=['number', 'color'])

In [5]:
data = io.StringIO('''Fruit,Color,Count,Price
Apple,Red,3,$1.29
Apple,Green,9,$0.99
Pear,Red,25,$2.59
Pear,Green,26,$2.79
Lime,Green,99,$0.39
''')
df_unindexed = pd.read_csv(data)
df_unindexed

Fruit  Color  Count  Price
0  Apple    Red      3  $1.29
1  Apple  Green      9  $0.99
2   Pear    Red     25  $2.59
3   Pear  Green     26  $2.79
4   Lime  Green     99  $0.39

In [9]:
band_columns=pd.MultiIndex.from_product([['g','r','i','z'],
                                       ['MODEL_MAG','MODEL_MAGERR','MAG_LAMBDA_ERR']],
                                     names=['band','data'])

In [11]:
pz_bins=[m+str(n) for m,n in zip(['pz_bins_']*21,range(21))]
pz_val =[m+str(n) for m,n in zip(['pz_bins_']*21,range(21))]
pz_columns=pd.MultiIndex.from_product([pz_bins,
                                       ['MODEL_MAG','MODEL_MAGERR','MAG_LAMBDA_ERR']],
                                     names=['band','data'])

In [14]:
alt_bins=[m+str(n) for m,n in zip(['alt_']*5,range(5))]
alt_columns=pd.MultiIndex.from_product([pz_bins,
                                       ['MODEL_MAG','MODEL_MAGERR','MAG_LAMBDA_ERR']],
                                     names=['band','data'])

In [30]:
print(center['(ID_CENT,0)'])

0       3089939451
1       3047101906
2       3069562192
3       3092286075
4       3138662814
5       3119806344
6       3008918135
7       3020459591
8       3010448045
9       3157162066
10      3070344110
11      3016466598
12      3034626206
13      3008565300
14      3129061131
15      3058900488
16      3155750926
17      3119773430
18      3038715907
19      3091623101
20      3147350726
21      3088730045
22      3038560090
23      3033998639
24      3148132353
25      3105157976
26      3082542813
27      3098478675
28      3111484896
29      3158368426
           ...    
7036    3049418198
7037    3089665500
7038    3129320419
7039    3032565609
7040    3044388739
7041    3108788531
7042    3028295834
7043    3044677347
7044    3072219615
7045    3032080379
7046    3083393436
7047    3157143483
7048    3048844388
7049    3104118364
7050    3070443273
7051    3158247805
7052    3109678113
7053    3127212155
7054    3034346942
7055    3034337303
7056    3151673825
7057    3156

In [15]:
class Template(object):

    def __init__(self):
        self.value = "hello"
        self.other_value = "bonjour"
        self.constant_value = 42
        current_class = self.__class__
        inits = []
        while (current_class.__name__ != "Template"):
            inits.append(current_class.init)
            current_class = current_class.__bases__[0]
        for i in reversed(inits):
            i(self)

    def init(self):
        pass

    def info(self):
        print self.value
        print self.other_value
        print self.constant_value
        print ""    

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.value)? (<ipython-input-15-650d04f893c0>, line 19)

In [5]:
a=np.array([1,2,3])
b=np.array([2,3])
tlist=[a,b]

In [6]:
np.concatenate(tlist)

array([1, 2, 3, 2, 3])

In [7]:
type(tlist)

list

In [1]:
import numpy as np

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[10,11]]])

In [5]:
np.sum(a,axis=0)

array([[15, 18],
       [20, 23]])

In [9]:
a[:,:,1]

array([[ 2,  4],
       [ 6,  8],
       [10, 11]])

In [2]:
from tqdm.notebook import trange, tqdm
from time import sleep

for i in trange(3, desc='1st loop'):
    for j in tqdm(range(100), desc='2nd loop'):
        sleep(0.01)

KeyboardInterrupt: 

In [1]:
from ipywidgets import Button

Button()

Button(style=ButtonStyle())

In [7]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.empty([20,3,2])

In [10]:
b[0,:,:]=a

In [11]:
b

array([[[1.00000000e+000, 2.00000000e+000],
        [3.00000000e+000, 4.00000000e+000],
        [5.00000000e+000, 6.00000000e+000]],

       [[4.94065646e-324, 4.68163598e-310],
        [6.92322347e-310, 6.92323407e-310],
        [6.92322347e-310, 4.68163598e-310]],

       [[1.97626258e-323, 4.68154711e-310],
        [6.92322723e-310,             nan],
        [4.94065646e-324, 4.24399158e-314]],

       [[4.68154711e-310, 4.68163598e-310],
        [6.92323405e-310, 4.68154711e-310],
        [4.24399158e-314, 4.94065646e-324]],

       [[4.68163598e-310, 1.48219694e-323],
        [4.68163598e-310, 4.68163598e-310],
        [4.68163598e-310, 8.39911598e-323]],

       [[4.68163493e-310, 4.68163598e-310],
        [4.68154711e-310, 2.54639495e-313],
        [8.39911598e-323, 4.68163493e-310]],

       [[2.75859453e-313, 4.68154711e-310],
        [3.18299369e-313, 8.39911598e-323],
        [4.68163493e-310, 3.18299369e-313]],

       [[4.68154711e-310, 3.60739284e-313],
        [1.4327903